# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorting-hat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# import sortinghat.py
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 90, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.sort)

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 180, 171, 251))
        self.textEdit.setText("")
        self.textEdit.setObjectName("label")

        # self.label = QtWidgets.QLabel(self.centralwidget)
        # self.label.setGeometry(QtCore.QRect(50, 180, 571, 251))
        # self.label.setText("")
        # self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sorting hat"))
        self.pushButton.setText(_translate("MainWindow", "Sort"))

    def sort(self):
        student_list = ["Mark", "Amber", "Todd", "Anita", "Sandy", "Mike", "John", "Mary", "Stephen", "Sam",
                    "Ann", "Lisa", "Adam", "Jerrard", "Brook", "Dan", "Don", "May", "Boy", "Nat",
                    "Art", "Tom", "Judy", "Mick", "Joy", "Brad", "David", "Alex", "Tum", "Not",
                    "Big", "Jom", "Tong", "Top", "Samuel", "Sea", "Sun", "Fluke", "Max", "Patt",
                    "Peter", "Josh", "Kathy", "Golf", "Kavin", "Roy", "Yo", "Luka", "Lucy", "Beck"            
                ]

        Gryffindor = []
        Hufflepuff = []
        Ravenclaw = []
        Slytherin = []
        house_list = [Gryffindor, Hufflepuff, Ravenclaw, Slytherin]
        house_list2= [Gryffindor, Hufflepuff, Ravenclaw, Slytherin]
        house_namelist = ["Gryffindor", "Hufflepuff", "Ravenclaw", "Slytherin"]
                

        for student in student_list:
            house = random.choice(house_list)
            if len(house) > 12:
                house_list.remove(house)
                house = random.choice(house_list)
            else:
                pass
            house.append(student)
        result = ''        
        for (value1, value2) in enumerate(zip(house_namelist, house_list2)): 
            resul = str(value2[0] +" has "+ str(len(value2[1])) +" students ")
            print(value2[0] +" has "+ str(len(value2[1])) +" students ")
            result += resul
        print(result)    
        # self.label.setText(result)
        self.textEdit.setText(result)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
